export * from './Ground';
export * from './Clouds';
export * from './Wrapper';
export * from './Dino';
export * from './Trees';
export * from './Game';
export * from './GameOver';
export * from './BtnRestart';
export * from './Birds';